In [207]:
U = [1 -im 0; 0 im 0; 0 -1 0]

3×3 Array{Complex{Int64},2}:
 1+0im   0-1im  0+0im
 0+0im   0+1im  0+0im
 0+0im  -1+0im  0+0im

In [208]:
H = [0 1-im 0; 1+im 0 2-2im; 0 2+2im 0 ]

3×3 Array{Complex{Int64},2}:
 0+0im  1-1im  0+0im
 1+1im  0+0im  2-2im
 0+0im  2+2im  0+0im

In [209]:
U * U'

3×3 Array{Complex{Int64},2}:
  2+0im  -1+0im  0+1im
 -1+0im   1+0im  0-1im
  0-1im   0+1im  1+0im

In [210]:
U * H * U'

3×3 Array{Complex{Int64},2}:
  2+0im  -1-1im  -1+1im
 -1+1im   0+0im   0+0im
 -1-1im   0+0im   0+0im

In [231]:
els = [0, -1, 1, im, -im]
U = zeros(ComplexF64, 3, 3)
H = [0 1-im 0; 1+im 0 2-2im; 0 2+2im 0]
Hideal1 = [1 1 0; 1 2 0; 0 2 0]
Hideal2 = [0 1 0; 1 1 0; 0 2 2]
Hideal3 = [0 1 0; 1 2 0; 0 2 1];

In [236]:
cutoff = 1e9
i = 0
while true
    i += 1
    for i in 1:3, j in 1:3
        U[i, j] = rand(els)
    end
    F = U * H * U'
    if F == Hideal1 || F == Hideal2 || F == Hideal3
        print(U)
        break
    elseif F[1,2] == 1 && F[2,1] == 1 && F[2,3] == 2 && F[3,2] == 2 && F[1,3] == 0 && F[3,1] == 0
        print(U)
        break
    elseif i > cutoff
        break
    end
end
    